### PR TITLE
Basis for the group manager view

### PR DESCRIPTION
**Pull request by vjrantal**
Contains a baseline for visualizing data in the group manager view, but does not yet implement the functionality to edit the data. That requires support in the REST API for the needed operations.

The content of this pull request implements parts of https://github.com/SimpleCloudManagerProject/SCAMP/issues/128.

### CODE REVIEW

**Comment by vjrantal** [comment]
The implementation differs a bit from the given wireframe mainly in the members tab that currently looks like this:

screen shot 2015-06-12 at 12 57 06

The key point I'd like to raise for discussion is the role column in the above screen shot.

The idea in the current implementation is that a group has members where a member can be either:

1. User
2. Group Manager
3. Group Admin

The names in the above list are same as what is used on this page http://www.simplecloudmgr.org/docs/features/resourceusage/ .

Depending on what is the role of the currently logged in user in the currently selected group, a role of a member can be potentially changed. For example, An admin could change a user to be a manager, but a user wouldn't be given such option.

@erikschlegel, @brentstineman: What do you think about this kind of model? If you agree on the approach, I'll post the specification of the REST API that I think would fit well to implement accordingly.

**Comment by brentstineman** [comment]
Group managers can only be appointed by the system admin and we have the UI for appointing those already constructed under “system settings”. So I think a simple yes/no checkbox for identifying group admins will be sufficient. :)

**Comment by vjrantal** [comment]
> Group managers can only be appointed by the system admin and we have the UI for appointing those already constructed under “system settings”. So I think a simple yes/no checkbox for identifying group admins will be sufficient. :)

Got it. As discussed, there was some mismatch on terms used in wireframes, other views and documentation. After getting this clarified, the I fixed the view to look like this:

screen shot 2015-06-12 at 15 22 29

There is an explicit save-button on the top, because I thought it results into simpler implementation and user experience compared to us updating data to the REST API every time user checks these checkboxes or edits any of the fields.

**Comment by vjrantal** [comment]
@brentstineman: Here is my views on how the REST API could look like to implement the group management.

Adding following properties to the group object the API already responds:

https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L113
https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L124
https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L125
https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L126

The group object should include a users property which has the following properties:

https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L118-L121

In addition, these POST, PUT and DELETE requests should be supported:

https://gist.github.com/vjrantal/22e1ebf27a9481750955#file-dev-js-L129-L164

**Pull request merged**
