### PR TITLE
Fix issue #171.

### PR DESCRIPTION
**Pull request by vjrantal**
When the page was reloaded, the dashboard controller tried to access
the user profile before it was returned from the API. This resulted into
a JavaScript error and prevented the rest of the dashboard functionality.

This change adds an event to be broadcasted from homeCtrl.js that is
listened for in case the user profile is not yet fetched.

### CODE REVIEW

**Comment by vjrantal** [comment]
@erikschlegel: Just noticed that after a logout -> login, the dashboard isn't updated automatically so will still tweak the implementation a bit to fix that scenario.

**Comment by brentstineman** [comment]
This PR also closes #170

**Comment by erikschlegel** [comment]
Slick Solution Ville.

**Comment by vjrantal** [comment]
Thanks for the feedback and for merging this one.

> Just noticed that after a logout -> login, the dashboard isn't updated automatically

This isn't a regression from this pull request, but a different issue that existed already before so will fix it separately.

**Pull request merged**
