### PR TITLE
System Administrator Maintenance

### PR DESCRIPTION
**Pull request by brentstineman**
Partial implementation of #73 and #71

### CODE REVIEW

**Comment by stuartleeks** [comment]
Hey Brent,

A few questions/notes:
*  ScampUser derives from Document - was there a reason for this? The other entities don't
*  SystemSettingsController.grantAdmin. The normal casing for the method would be "GrantAdmin"
*  SystemSettingsController.grantAdmin. Should we have some security on this method to limit who can grant a user admin permissions? ;-)
*  SystemSettingsController.Get. Personally I'd use LINQ's Select to map the List from the repository into the model type you're returning. (As a side note, we should consider introducing automapper as well :-))
*  settingsAdminsCtrl.js there is some logic to ensure that there is always at least one admin. We should have this in the API too

Stuart

**Comment by brentstineman** [comment]
1) this allows a single doc to be fetched, altered, and saved. IMHO, the approach minimizes the risk of change overlay/loss as otherwise we have to fetch the doc, alter it, fetch the doc again and then update the doc using the originally fetched/altered version. The key component missing if we don't inherit from Document is the "selflink" property.
2) easy to change. :) 
3) eventually, yes. But since I'm still getting that level of security built, I figured I'd get the add/remove working them start wiring up more security implementation
4) can you point me at another example? I simply reused what we had elsewhere
5) agreed, I'll look for a cost affective way to enforce that today.

**Comment by stuartleeks** [comment]
Re 4) take a look at GroupsController.Get. It's using LINQ's select to project the data into a different shape. I've put the projection into a separate function, but since I'm not reusing it here (yet) that's largely stylistic

I also noticed that the IsSytemAdmin is being serialised with PascalCase rather than camelCase. This deviates from the other properties, so would be good to make them consistent :-)

**Comment by brentstineman** [comment]
Thanks Stuart. I’m on these recommendations. Thanks for the diligence.

**Comment by brentstineman** [comment]
Check it now Stuart. I think I've addressed all the issues that were raised. :)

**Comment by cicorias** [comment]
In ```UserController.cs``` there's an API key hardcoded and the paths are hardcoded to. these things should be externalized and the api key never checked in.

Also in ```UsersController.cs``` - there should be disposing of some ```IDisposable``` things. I thought this was changed to HttpClient.

This call should be async as well ```string result = response.ReadAsStringAsync().Result;``` 

In general while these classes implement ```IDisposable``` they also maintain HTTP connections - which is limited by ```ServicePointManager.DefaultMaxConnectionsPerServer``` and that is '2' by default.

**Comment by brentstineman** [comment]
Thanks Shawn, I'll regen the search key to prevent issues there. I had intended to move that over to a config setting but didn't think of that in the latest commit. 

As for the http connection, i'm not sure what connection is being maintained. I'll try to dig into it more but once we get the response, the connection should be closed. If the httpclient is keeping that connection 'open', then I have concerned.

**Comment by brentstineman** [comment]
search key regen'd and one note updated.

**Comment by cicorias** [comment]
Inside of HttpRequest there are connections maintained for at least some time.  When using HttpClient which abstracts all that.  So, a singleton will help and that's the advice of the MVC team that created it.

While HttpClient does implement ```IDisposable``` it has resource challenges with tasks (not officially leakage) when using Dispose.  And, it was designed and tested to be held on for a long time and re-used within an application. Check the first answer [here](http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed)  also look at this [here](http://chimera.labs.oreilly.com/books/1234000001708/ch14.html#_creating_resuable_response_handlers)

ServicePointManager.DefaultPersistentConnectionLimit Field also default is 2.  And has to be set at the beginning of a clr process.

**Comment by brentstineman** [comment]
Thanks Shawn. I'll just remove the search calls for the moment until we have time to submit them as a fully backed solution call. That is *if* I can get this PR to the point where it can be accepted/merged. :)

**Comment by cicorias** [comment]
regardless, you still need to set ```ServicePointManager.DefaultPersistentConnectionLimit Field``` also default is 2. And has to be set at the beginning of a clr process.

somewhere in AppStart

**Comment by brentstineman** [comment]
Merging to get into base code. If there are still remaining issues, please open them. Thx.

**Pull request merged**
