### PR TITLE
requested API changes and partial API security implementation

### PR DESCRIPTION
**Pull request by brentstineman**
changes related to requested API changes (PR #204) and partial implementation of #168 (api security implementation)

@vjrantal this includes the changes you requested in PR #204

### CODE REVIEW

**Comment by vjrantal** [comment]
I tested these out and initial testing revealed these deviations from what I tried to request:

* Responses have property called `expirtyDate`, but it should be `expiryDate`
* The response to PUT request was 204 with empty content and not the group object
* The response to POST didn't contain a full group object, but just a few properties
* After adding a group, the person who added it was not added as a manager of the group
* Group object has `members` property and not `users` property
* Groups are not persisted after a new group is POST'ed

The deletion resulted into 404 not found error, but this might relate to groups not getting persisted in the first place.

You can test the API with my current front-end code by taking this commit https://github.com/vjrantal/SCAMP/commit/2da8e2553be12e55a8e675a3415633039f1f9c18. This doesn't yet include any of the functionality in the users-tab, but should contain most of what one can do in the summary-tab.

**Comment by brentstineman** [comment]
I can't find any mention of "expirtyDate", but will keep looking. 

For the put/post, we may want to consider separating the users out, updating user group membership as a separate API call. This will simplify the update process and allow for more atomic operations on the user list. Thoughts?

Two groups appear to have been created (looking at the data). So something is being persisted and we'll need to look into that more closely. 

Working on the others. I was a bit too focused and only worked on the API request signatures, not the implementations or responses. Will correct.

**Comment by vjrantal** [comment]
> I can't find any mention of "expirtyDate", but will keep looking.

https://github.com/brentstineman/SCAMP/commit/08bb85630989b045b36633c42183d198d95ec679#diff-6716d87b6cfeabc08f4b581bce0113dbR159

> For the put/post, we may want to consider separating the users out, updating user group membership as a separate API call. This will simplify the update process and allow for more atomic operations on the user list. Thoughts?

In the proposal I made, they are separate. There is a REST resource that ends with groups and one that ends with users. The latter is used to manage memberships.

> Two groups appear to have been created (looking at the data). So something is being persisted and we'll need to look into that more closely.

Good to know they got into the backend. Perhaps it is then in the "returning side" why the API doesn't give them out.

**Comment by brentstineman** [comment]
Still incomplete, but accepting so more hands can share the load on these changes.

**Pull request merged**
