### PR TITLE
Fix adding system and group admins.

### LINKED ISSUE #237: twitter type ahead control not working
the twitter typeahead control is able to call the /api/users/getuserbyupn api due to the fact it is not sending the authorization header/token in the request. This is affecting items group admin (#168) and system admin functionality.

### PR DESCRIPTION
**Pull request by vjrantal**
This fixes #237 that was occurring, because the previous typeahead
component did work out-of-box with the authentication mechanism used.

This commit also addresses some problems introduced by a renaming done
in #221 and improves the styling of the views where the Typeahead is used.

### CODE REVIEW

**Comment by vjrantal** [comment]
@brentstineman When I was testing this one, I noticed that there is still some issue when deleting system and group admins. The response I got from the server to an HTTP DELETE was 404.

Other than that, based on my testing, adding system and group admins was possible, but I would appreciate if someone could do a bit of manual testing, because there was some amount of variable naming fixes and I'd like to know if I got them right or not.

**Comment by brentstineman** [comment]
I'll do more on this one for you @vjrantal.

**Comment by brentstineman** [comment]
I had to manually merge this one. @vjrantal please review and ensure it was merged properly.

**Comment by vjrantal** [comment]
With a quick look, it seems okay.

**Pull request merged**
